

DECLARE @ID BIGINT = NULL
DECLARE @Url NVARCHAR(1000) = 'Url 7869df0429d9437cbb127a2308f13378'
DECLARE @Order INT = 64
DECLARE @ImageID BIGINT = 100012
 

DELETE FROM [ImageThumbnail]
FROM 
	[dbo].[ImageThumbnail] e
WHERE
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Order IS NOT NULL THEN (CASE WHEN [Order] = @Order THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @ImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
