

DECLARE @ID BIGINT = NULL
DECLARE @Url NVARCHAR(1000) = 'Url 5716fc26e7594ea18e0dbfc47b2c29af'
DECLARE @Order INT = 350
DECLARE @ImageID BIGINT = 100005
 

DELETE FROM [ImageThumbnail]
FROM 
	[dbo].[ImageThumbnail] e
WHERE
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Order IS NOT NULL THEN (CASE WHEN [Order] = @Order THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @ImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
