


DECLARE @ID BIGINT = NULL
DECLARE @CategoryName NVARCHAR(50) = 'CategoryName fca4bd9392684313b4e7b4a7f694e0ba'
DECLARE @Description NVARCHAR(1000) = 'Description fca4bd9392684313b4e7b4a7f694e0ba'
DECLARE @ParentID BIGINT = 100010
DECLARE @IsDeleted BIT = 1
DECLARE @CreatedDate DATETIME = '7/24/2021 7:01:38 AM'
DECLARE @CreatedByID BIGINT = 100002
DECLARE @ModifiedDate DATETIME = '6/8/2019 1:16:38 PM'
DECLARE @ModifiedByID BIGINT = 100008
 

DELETE FROM [Category]
FROM 
	[dbo].[Category] e
WHERE
	(CASE WHEN @CategoryName IS NOT NULL THEN (CASE WHEN [CategoryName] = @CategoryName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Description IS NOT NULL THEN (CASE WHEN [Description] = @Description THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ParentID IS NOT NULL THEN (CASE WHEN [ParentID] = @ParentID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
