

DECLARE @ID BIGINT = NULL
DECLARE @MatName NVARCHAR(50) = 'MatName 309a5a43c2ee47ae8f1a14445f5bc50b'
DECLARE @Description NVARCHAR(1000) = 'Description 309a5a43c2ee47ae8f1a14445f5bc50b'
DECLARE @ThumbnailUrl NVARCHAR(1000) = 'ThumbnailUrl 309a5a43c2ee47ae8f1a14445f5bc50b'
DECLARE @IsDeleted BIT = 0
DECLARE @CreatedDate DATETIME = '6/22/2022 7:34:33 PM'
DECLARE @CreatedByID BIGINT = 100009
DECLARE @ModifiedDate DATETIME = '2/2/2021 3:09:33 AM'
DECLARE @ModifiedByID BIGINT = 100009
 

DELETE FROM [Mat]
FROM 
	[dbo].[Mat] e
WHERE
	(CASE WHEN @MatName IS NOT NULL THEN (CASE WHEN [MatName] = @MatName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Description IS NOT NULL THEN (CASE WHEN [Description] = @Description THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ThumbnailUrl IS NOT NULL THEN (CASE WHEN [ThumbnailUrl] = @ThumbnailUrl THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
