

DECLARE @ID BIGINT = NULL
DECLARE @MatName NVARCHAR(50) = 'MatName 6496f94b17194c01aec7d0c937bc9bf3'
DECLARE @Description NVARCHAR(1000) = 'Description 6496f94b17194c01aec7d0c937bc9bf3'
DECLARE @ThumbnailUrl NVARCHAR(1000) = 'ThumbnailUrl 6496f94b17194c01aec7d0c937bc9bf3'
DECLARE @IsDeleted BIT = 0
DECLARE @CreatedDate DATETIME = '10/11/2023 3:09:48 AM'
DECLARE @CreatedByID BIGINT = 100005
DECLARE @ModifiedDate DATETIME = '1/8/2020 6:45:48 AM'
DECLARE @ModifiedByID BIGINT = 100008
 

DELETE FROM [Mat]
FROM 
	[dbo].[Mat] e
WHERE
	(CASE WHEN @MatName IS NOT NULL THEN (CASE WHEN [MatName] = @MatName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Description IS NOT NULL THEN (CASE WHEN [Description] = @Description THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ThumbnailUrl IS NOT NULL THEN (CASE WHEN [ThumbnailUrl] = @ThumbnailUrl THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
