

DECLARE @ID BIGINT = NULL
DECLARE @OrderID BIGINT = 100006
DECLARE @OrderStatusID BIGINT = 7
DECLARE @SetDate DATETIME = '8/17/2022 1:28:49 AM'
DECLARE @SetByID BIGINT = 100009
DECLARE @Comment NVARCHAR(1000) = 'Comment 1f394bef18574ef69e69cba4c588f1c0'
 


IF(NOT EXISTS(SELECT 1 FROM 
					[dbo].[OrderTracking]
				WHERE 
	(CASE WHEN @OrderID IS NOT NULL THEN (CASE WHEN [OrderID] = @OrderID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @OrderStatusID IS NOT NULL THEN (CASE WHEN [OrderStatusID] = @OrderStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SetDate IS NOT NULL THEN (CASE WHEN [SetDate] = @SetDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SetByID IS NOT NULL THEN (CASE WHEN [SetByID] = @SetByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Comment IS NOT NULL THEN (CASE WHEN [Comment] = @Comment THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN
	INSERT INTO [dbo].[OrderTracking]
		(
	 [OrderID],
	 [OrderStatusID],
	 [SetDate],
	 [SetByID],
	 [Comment]
		)
	SELECT 		
			 @OrderID,
	 @OrderStatusID,
	 @SetDate,
	 @SetByID,
	 @Comment
END

SELECT TOP 1 
	@ID = [ID]
FROM 
	[dbo].[OrderTracking] e
WHERE
	(CASE WHEN @OrderID IS NOT NULL THEN (CASE WHEN [OrderID] = @OrderID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @OrderStatusID IS NOT NULL THEN (CASE WHEN [OrderStatusID] = @OrderStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SetDate IS NOT NULL THEN (CASE WHEN [SetDate] = @SetDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SetByID IS NOT NULL THEN (CASE WHEN [SetByID] = @SetByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Comment IS NOT NULL THEN (CASE WHEN [Comment] = @Comment THEN 1 ELSE 0 END) ELSE 1 END) = 1 

SELECT 
	@ID
