


-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @OrderID BIGINT = 100011
DECLARE @ImageID BIGINT = 100027
DECLARE @Width INT = 664
DECLARE @Height INT = 664
DECLARE @SizeID BIGINT = 100001
DECLARE @FrameTypeID BIGINT = 100016
DECLARE @FrameSizeID BIGINT = 100010
DECLARE @MatID BIGINT = 100007
DECLARE @MaterialTypeID BIGINT = 100005
DECLARE @MountingTypeID BIGINT = 100004
DECLARE @ItemCount INT = 187
DECLARE @PriceAmountPerItem DECIMAL(18, 2) = 186423.88
DECLARE @PriceCurrencyID BIGINT = 11
DECLARE @Comments NVARCHAR(1000) = 'Comments e30c3b91d38f452c937e7692c38dc313'
DECLARE @PrintingHouseID BIGINT = 100001
DECLARE @IsDeleted BIT = 1
DECLARE @CreatedDate DATETIME = '12/26/2022 10:41:39 PM'
DECLARE @CreatedByID BIGINT = 100005
DECLARE @ModifiedDate DATETIME = '12/26/2022 10:41:39 PM'
DECLARE @ModifiedByID BIGINT = 100011
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updOrderID BIGINT = 100012
DECLARE @updImageID BIGINT = 100038
DECLARE @updWidth INT = 232
DECLARE @updHeight INT = 232
DECLARE @updSizeID BIGINT = 100011
DECLARE @updFrameTypeID BIGINT = 100008
DECLARE @updFrameSizeID BIGINT = 100011
DECLARE @updMatID BIGINT = 100004
DECLARE @updMaterialTypeID BIGINT = 100002
DECLARE @updMountingTypeID BIGINT = 100006
DECLARE @updItemCount INT = 276
DECLARE @updPriceAmountPerItem DECIMAL(18, 2) = 276125.14
DECLARE @updPriceCurrencyID BIGINT = 63
DECLARE @updComments NVARCHAR(1000) = 'Comments 0f838a8a0585484f9939c89a58fbdc15'
DECLARE @updPrintingHouseID BIGINT = 100005
DECLARE @updIsDeleted BIT = 0
DECLARE @updCreatedDate DATETIME = '6/25/2023 4:28:39 AM'
DECLARE @updCreatedByID BIGINT = 100002
DECLARE @updModifiedDate DATETIME = '11/11/2020 2:15:39 PM'
DECLARE @updModifiedByID BIGINT = 100003
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[OrderItem]
				WHERE 
	(CASE WHEN @updOrderID IS NOT NULL THEN (CASE WHEN [OrderID] = @updOrderID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @updImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updWidth IS NOT NULL THEN (CASE WHEN [Width] = @updWidth THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updHeight IS NOT NULL THEN (CASE WHEN [Height] = @updHeight THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSizeID IS NOT NULL THEN (CASE WHEN [SizeID] = @updSizeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFrameTypeID IS NOT NULL THEN (CASE WHEN [FrameTypeID] = @updFrameTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFrameSizeID IS NOT NULL THEN (CASE WHEN [FrameSizeID] = @updFrameSizeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMatID IS NOT NULL THEN (CASE WHEN [MatID] = @updMatID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMaterialTypeID IS NOT NULL THEN (CASE WHEN [MaterialTypeID] = @updMaterialTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMountingTypeID IS NOT NULL THEN (CASE WHEN [MountingTypeID] = @updMountingTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updItemCount IS NOT NULL THEN (CASE WHEN [ItemCount] = @updItemCount THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPriceAmountPerItem IS NOT NULL THEN (CASE WHEN [PriceAmountPerItem] = @updPriceAmountPerItem THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPriceCurrencyID IS NOT NULL THEN (CASE WHEN [PriceCurrencyID] = @updPriceCurrencyID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updComments IS NOT NULL THEN (CASE WHEN [Comments] = @updComments THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPrintingHouseID IS NOT NULL THEN (CASE WHEN [PrintingHouseID] = @updPrintingHouseID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @updIsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[OrderItem]
	WHERE 
	(CASE WHEN @OrderID IS NOT NULL THEN (CASE WHEN [OrderID] = @OrderID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @ImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Width IS NOT NULL THEN (CASE WHEN [Width] = @Width THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Height IS NOT NULL THEN (CASE WHEN [Height] = @Height THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @SizeID IS NOT NULL THEN (CASE WHEN [SizeID] = @SizeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FrameTypeID IS NOT NULL THEN (CASE WHEN [FrameTypeID] = @FrameTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FrameSizeID IS NOT NULL THEN (CASE WHEN [FrameSizeID] = @FrameSizeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MatID IS NOT NULL THEN (CASE WHEN [MatID] = @MatID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MaterialTypeID IS NOT NULL THEN (CASE WHEN [MaterialTypeID] = @MaterialTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MountingTypeID IS NOT NULL THEN (CASE WHEN [MountingTypeID] = @MountingTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ItemCount IS NOT NULL THEN (CASE WHEN [ItemCount] = @ItemCount THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @PriceAmountPerItem IS NOT NULL THEN (CASE WHEN [PriceAmountPerItem] = @PriceAmountPerItem THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @PriceCurrencyID IS NOT NULL THEN (CASE WHEN [PriceCurrencyID] = @PriceCurrencyID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Comments IS NOT NULL THEN (CASE WHEN [Comments] = @Comments THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @PrintingHouseID IS NOT NULL THEN (CASE WHEN [PrintingHouseID] = @PrintingHouseID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[OrderItem]
	WHERE 
	(CASE WHEN @updOrderID IS NOT NULL THEN (CASE WHEN [OrderID] = @updOrderID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @updImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updWidth IS NOT NULL THEN (CASE WHEN [Width] = @updWidth THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updHeight IS NOT NULL THEN (CASE WHEN [Height] = @updHeight THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSizeID IS NOT NULL THEN (CASE WHEN [SizeID] = @updSizeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFrameTypeID IS NOT NULL THEN (CASE WHEN [FrameTypeID] = @updFrameTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFrameSizeID IS NOT NULL THEN (CASE WHEN [FrameSizeID] = @updFrameSizeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMatID IS NOT NULL THEN (CASE WHEN [MatID] = @updMatID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMaterialTypeID IS NOT NULL THEN (CASE WHEN [MaterialTypeID] = @updMaterialTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMountingTypeID IS NOT NULL THEN (CASE WHEN [MountingTypeID] = @updMountingTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updItemCount IS NOT NULL THEN (CASE WHEN [ItemCount] = @updItemCount THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPriceAmountPerItem IS NOT NULL THEN (CASE WHEN [PriceAmountPerItem] = @updPriceAmountPerItem THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPriceCurrencyID IS NOT NULL THEN (CASE WHEN [PriceCurrencyID] = @updPriceCurrencyID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updComments IS NOT NULL THEN (CASE WHEN [Comments] = @updComments THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPrintingHouseID IS NOT NULL THEN (CASE WHEN [PrintingHouseID] = @updPrintingHouseID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @updIsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'OrderItem was not updated', 1
END