

DECLARE @ID BIGINT = NULL
DECLARE @ContactTypeID BIGINT = 6
DECLARE @Title NVARCHAR(50) = 'Title 05698bbe54ef41769b7fa9bf81adb445'
DECLARE @Comment NVARCHAR(250) = 'Comment 05698bbe54ef41769b7fa9bf81adb445'
DECLARE @Value NVARCHAR(1000) = 'Value 05698bbe54ef41769b7fa9bf81adb445'
DECLARE @IsDeleted BIT = 1
DECLARE @CreatedByID BIGINT = 100008
DECLARE @CreatedDate DATETIME = '12/26/2022 7:04:48 AM'
DECLARE @ModifiedByID BIGINT = 100009
DECLARE @ModifiedDate DATETIME = '11/5/2021 10:13:48 AM'
 

DELETE FROM [Contact]
FROM 
	[dbo].[Contact] e
WHERE
	(CASE WHEN @ContactTypeID IS NOT NULL THEN (CASE WHEN [ContactTypeID] = @ContactTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Title IS NOT NULL THEN (CASE WHEN [Title] = @Title THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Comment IS NOT NULL THEN (CASE WHEN [Comment] = @Comment THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Value IS NOT NULL THEN (CASE WHEN [Value] = @Value THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 
