bcp PhotoPrint.dbo.Address format nul -c -f .\TestData\Address.fmt -t, -T
bcp PhotoPrint.dbo.Category format nul -c -f .\TestData\Category.fmt -t, -T
bcp PhotoPrint.dbo.Contact format nul -c -f .\TestData\Contact.fmt -t, -T
bcp PhotoPrint.dbo.DeliveryService format nul -c -f .\TestData\DeliveryService.fmt -t, -T
bcp PhotoPrint.dbo.DeliveryServiceCity format nul -c -f .\TestData\DeliveryServiceCity.fmt -t, -T
bcp PhotoPrint.dbo.FrameType format nul -c -f .\TestData\FrameType.fmt -t, -T
bcp PhotoPrint.dbo.Image format nul -c -f .\TestData\Image.fmt -t, -T
bcp PhotoPrint.dbo.ImageCategory format nul -c -f .\TestData\ImageCategory.fmt -t, -T
bcp PhotoPrint.dbo.ImageRelated format nul -c -f .\TestData\ImageRelated.fmt -t, -T
bcp PhotoPrint.dbo.ImageThumbnail format nul -c -f .\TestData\ImageThumbnail.fmt -t, -T
bcp PhotoPrint.dbo.Mat format nul -c -f .\TestData\Mat.fmt -t, -T
bcp PhotoPrint.dbo.MaterialType format nul -c -f .\TestData\MaterialType.fmt -t, -T
bcp PhotoPrint.dbo.MountingType format nul -c -f .\TestData\MountingType.fmt -t, -T
bcp PhotoPrint.dbo.[Order] format nul -c -f .\TestData\Order.fmt -t, -T
bcp PhotoPrint.dbo.OrderItem format nul -c -f .\TestData\OrderItem.fmt -t, -T
bcp PhotoPrint.dbo.OrderPaymentDetails format nul -c -f .\TestData\OrderPaymentDetails.fmt -t, -T
bcp PhotoPrint.dbo.OrderStatusFlow format nul -c -f .\TestData\OrderStatusFlow.fmt -t, -T
bcp PhotoPrint.dbo.OrderTracking format nul -c -f .\TestData\OrderTracking.fmt -t, -T
bcp PhotoPrint.dbo.PrintingHouse format nul -c -f .\TestData\PrintingHouse.fmt -t, -T
bcp PhotoPrint.dbo.PrintingHouseAddress format nul -c -f .\TestData\PrintingHouseAddress.fmt -t, -T
bcp PhotoPrint.dbo.PrintingHouseContact format nul -c -f .\TestData\PrintingHouseContact.fmt -t, -T
bcp PhotoPrint.dbo.Size format nul -c -f .\TestData\Size.fmt -t, -T
bcp PhotoPrint.dbo.[User] format nul -c -f .\TestData\User.fmt -t, -T
bcp PhotoPrint.dbo.UserAddress format nul -c -f .\TestData\UserAddress.fmt -t, -T
bcp PhotoPrint.dbo.UserConfirmation format nul -c -f .\TestData\UserConfirmation.fmt -t, -T
bcp PhotoPrint.dbo.UserContact format nul -c -f .\TestData\UserContact.fmt -t, -T