


DECLARE @FromStatusID BIGINT = 11
DECLARE @ToStatusID BIGINT = 5
 

DELETE FROM [OrderStatusFlow]
FROM 
	[dbo].[OrderStatusFlow] e
WHERE
	(CASE WHEN @FromStatusID IS NOT NULL THEN (CASE WHEN [FromStatusID] = @FromStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ToStatusID IS NOT NULL THEN (CASE WHEN [ToStatusID] = @ToStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
