


DECLARE @ID BIGINT = NULL
DECLARE @UserID BIGINT = 100009
DECLARE @Url NVARCHAR(1000) = 'Url a95b4a207dff4f1f83c05652210c9e7e'
 


IF(EXISTS(SELECT 1 FROM 
					[dbo].[UserInteriorThumbnail]
				WHERE 
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM [dbo].[UserInteriorThumbnail]
WHERE 
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 

END