apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-photoprint-api
    labels:
        app: ppt-photoprint-api
spec:
    replicas: 5
    selector:
        matchLabels:
            app: ppt-photoprint-api
    template:
        metadata:
            labels:
                app: ppt-photoprint-api
        spec:
            containers:
            - name: ppt-photoprint-api
              image: globus000/ppt.photoprint.api
              env:
              - name: ServiceConfig__DalInitParams__ConnectionString
                value: "Data Source=photoprint-sqlsrv.database.windows.net; Initial Catalog=PhotoPrint-DEV; User ID=ppt_svc_api; Password=PhotoPrint2021!"
              - name: ServiceConfig__StorageInitParams__StorageConnectionString
                value: "BlobEndpoint=https://photoprintstorage.blob.core.windows.net/;QueueEndpoint=https://photoprintstorage.queue.core.windows.net/;FileEndpoint=https://photoprintstorage.file.core.windows.net/;TableEndpoint=https://photoprintstorage.table.core.windows.net/;SharedAccessSignature=sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-12-05T04:11:36Z&st=2021-12-04T20:11:36Z&spr=https&sig=kZlrAy53M2nZF7YXrcKuOQuR70%%2Bea15mwD4i3ib860A%%3D"
              - name: ServiceConfig__StorageInitParams__StorageUrl
                value: "https://photoprintstorage.blob.core.windows.net"
              - name: ServiceConfig__StorageInitParams__ContainerName
                value: "photoprint-images-dev"
              ports:
              - containerPort: 8082
 
