apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment-photoprint-api
    labels:
        app: ppt-photoprint-api
spec:
    replicas: 5
    selector:
        matchLabels:
            app: ppt-photoprint-api
    template:
        metadata:
            labels:
                app: ppt-photoprint-api
        spec:
            containers:
            - name: ppt-photoprint-api
              image: globus000/ppt.photoprint.api
              env:
              - name: ServiceConfig__DalInitParams__ConnectionString
                value: "Data Source=host.minikube.internal; Initial Catalog=PhotoPrint; User ID=ppt_svc_api; Password=PPTServiceApi2021!"
              - name: ServiceConfig__StorageInitParams__StorageConnectionString
                value: "BlobEndpoint=http://host.minikube.internal:10000/devstoreaccount1;QueueEndpoint=http://host.minikube.internal:10001/devstoreaccount1;TableEndpoint=http://host.minikube.internal:10002/devstoreaccount1;DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;"
              - name: ServiceConfig__StorageInitParams__StorageUrl
                value: "http://127.0.0.1:10000/devstoreaccount1"
              - name: ServiceConfig__StorageInitParams__ContainerName
                value: "photoprint-images-dev"
              ports:
              - containerPort: 8082
 
