apiVersion: v1
kind: Service
metadata:
    name: lb-photoprint-api
    labels:
        run: lb-photoprint-api
spec:
    type: LoadBalancer
    selector:
        app: ppt-photoprint-api
    ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082