


-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @Login NVARCHAR(250) = 'Login fbba81d1c5df407889d455cf758324ac'
DECLARE @PwdHash NVARCHAR(250) = 'PwdHash fbba81d1c5df407889d455cf758324ac'
DECLARE @Salt NVARCHAR(50) = 'Salt fbba81d1c5df407889d455cf758324ac'
DECLARE @FirstName NVARCHAR(50) = 'FirstName fbba81d1c5df407889d455cf758324ac'
DECLARE @MiddleName NVARCHAR(50) = 'MiddleName fbba81d1c5df407889d455cf758324ac'
DECLARE @LastName NVARCHAR(50) = 'LastName fbba81d1c5df407889d455cf758324ac'
DECLARE @FriendlyName NVARCHAR(50) = 'FriendlyName fbba81d1c5df407889d455cf758324ac'
DECLARE @UserStatusID BIGINT = 2
DECLARE @UserTypeID BIGINT = 2
DECLARE @CreatedDate DATETIME = '4/12/2023 10:37:40 AM'
DECLARE @ModifiedDate DATETIME = '8/29/2020 11:04:40 AM'
DECLARE @ModifiedByID BIGINT = 100002
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updLogin NVARCHAR(250) = 'Login 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updPwdHash NVARCHAR(250) = 'PwdHash 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updSalt NVARCHAR(50) = 'Salt 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updFirstName NVARCHAR(50) = 'FirstName 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updMiddleName NVARCHAR(50) = 'MiddleName 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updLastName NVARCHAR(50) = 'LastName 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updFriendlyName NVARCHAR(50) = 'FriendlyName 41ccc074dd3843bea7aa3387a488f724'
DECLARE @updUserStatusID BIGINT = 2
DECLARE @updUserTypeID BIGINT = 5
DECLARE @updCreatedDate DATETIME = '7/10/2023 8:51:40 PM'
DECLARE @updModifiedDate DATETIME = '7/10/2023 8:51:40 PM'
DECLARE @updModifiedByID BIGINT = 100010
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[User]
				WHERE 
	(CASE WHEN @updLogin IS NOT NULL THEN (CASE WHEN [Login] = @updLogin THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @updPwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSalt IS NOT NULL THEN (CASE WHEN [Salt] = @updSalt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @updFriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @updUserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @updUserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[User]
	WHERE 
	(CASE WHEN @Login IS NOT NULL THEN (CASE WHEN [Login] = @Login THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @PwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @PwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Salt IS NOT NULL THEN (CASE WHEN [Salt] = @Salt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @FirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @MiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @LastName IS NOT NULL THEN (CASE WHEN [LastName] = @LastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @FriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @UserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @UserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[User]
	WHERE 
	(CASE WHEN @updLogin IS NOT NULL THEN (CASE WHEN [Login] = @updLogin THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @updPwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSalt IS NOT NULL THEN (CASE WHEN [Salt] = @updSalt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @updFriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @updUserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @updUserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'User was not updated', 1
END