

-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @Login NVARCHAR(250) = 'Login 09fd941b832c46f391a999459c80e8a3'
DECLARE @PwdHash NVARCHAR(250) = 'PwdHash 09fd941b832c46f391a999459c80e8a3'
DECLARE @Salt NVARCHAR(50) = 'Salt 09fd941b832c46f391a999459c80e8a3'
DECLARE @FirstName NVARCHAR(50) = 'FirstName 09fd941b832c46f391a999459c80e8a3'
DECLARE @MiddleName NVARCHAR(50) = 'MiddleName 09fd941b832c46f391a999459c80e8a3'
DECLARE @LastName NVARCHAR(50) = 'LastName 09fd941b832c46f391a999459c80e8a3'
DECLARE @FriendlyName NVARCHAR(50) = 'FriendlyName 09fd941b832c46f391a999459c80e8a3'
DECLARE @UserStatusID BIGINT = 2
DECLARE @UserTypeID BIGINT = 1
DECLARE @CreatedDate DATETIME = '2/1/2021 9:57:49 AM'
DECLARE @ModifiedDate DATETIME = '2/1/2021 9:57:49 AM'
DECLARE @ModifiedByID BIGINT = 100006
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updLogin NVARCHAR(250) = 'Login a60f1d045db94762ba2a95296f60fb80'
DECLARE @updPwdHash NVARCHAR(250) = 'PwdHash a60f1d045db94762ba2a95296f60fb80'
DECLARE @updSalt NVARCHAR(50) = 'Salt a60f1d045db94762ba2a95296f60fb80'
DECLARE @updFirstName NVARCHAR(50) = 'FirstName a60f1d045db94762ba2a95296f60fb80'
DECLARE @updMiddleName NVARCHAR(50) = 'MiddleName a60f1d045db94762ba2a95296f60fb80'
DECLARE @updLastName NVARCHAR(50) = 'LastName a60f1d045db94762ba2a95296f60fb80'
DECLARE @updFriendlyName NVARCHAR(50) = 'FriendlyName a60f1d045db94762ba2a95296f60fb80'
DECLARE @updUserStatusID BIGINT = 1
DECLARE @updUserTypeID BIGINT = 2
DECLARE @updCreatedDate DATETIME = '12/12/2023 10:23:49 AM'
DECLARE @updModifiedDate DATETIME = '12/12/2023 10:23:49 AM'
DECLARE @updModifiedByID BIGINT = 100007
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[User]
				WHERE 
	(CASE WHEN @updLogin IS NOT NULL THEN (CASE WHEN [Login] = @updLogin THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @updPwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSalt IS NOT NULL THEN (CASE WHEN [Salt] = @updSalt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @updFriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @updUserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @updUserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[User]
	WHERE 
	(CASE WHEN @Login IS NOT NULL THEN (CASE WHEN [Login] = @Login THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @PwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @PwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Salt IS NOT NULL THEN (CASE WHEN [Salt] = @Salt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @FirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @MiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @LastName IS NOT NULL THEN (CASE WHEN [LastName] = @LastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @FriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @UserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @UserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[User]
	WHERE 
	(CASE WHEN @updLogin IS NOT NULL THEN (CASE WHEN [Login] = @updLogin THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @updPwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSalt IS NOT NULL THEN (CASE WHEN [Salt] = @updSalt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @updFriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @updUserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @updUserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'User was not updated', 1
END