

-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @Login NVARCHAR(250) = 'Login 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @PwdHash NVARCHAR(250) = 'PwdHash 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @Salt NVARCHAR(50) = 'Salt 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @FirstName NVARCHAR(50) = 'FirstName 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @MiddleName NVARCHAR(50) = 'MiddleName 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @LastName NVARCHAR(50) = 'LastName 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @FriendlyName NVARCHAR(50) = 'FriendlyName 4fdb7a3c4a344ff38720dc4e7e11e8e7'
DECLARE @UserStatusID BIGINT = 1
DECLARE @UserTypeID BIGINT = 2
DECLARE @CreatedDate DATETIME = '4/16/2021 2:08:34 PM'
DECLARE @ModifiedDate DATETIME = '4/16/2021 2:08:34 PM'
DECLARE @ModifiedByID BIGINT = 100008
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updLogin NVARCHAR(250) = 'Login 31933898fd784a85bc9ac30b93269103'
DECLARE @updPwdHash NVARCHAR(250) = 'PwdHash 31933898fd784a85bc9ac30b93269103'
DECLARE @updSalt NVARCHAR(50) = 'Salt 31933898fd784a85bc9ac30b93269103'
DECLARE @updFirstName NVARCHAR(50) = 'FirstName 31933898fd784a85bc9ac30b93269103'
DECLARE @updMiddleName NVARCHAR(50) = 'MiddleName 31933898fd784a85bc9ac30b93269103'
DECLARE @updLastName NVARCHAR(50) = 'LastName 31933898fd784a85bc9ac30b93269103'
DECLARE @updFriendlyName NVARCHAR(50) = 'FriendlyName 31933898fd784a85bc9ac30b93269103'
DECLARE @updUserStatusID BIGINT = 4
DECLARE @updUserTypeID BIGINT = 4
DECLARE @updCreatedDate DATETIME = '2/25/2024 11:55:34 PM'
DECLARE @updModifiedDate DATETIME = '2/25/2024 11:55:34 PM'
DECLARE @updModifiedByID BIGINT = 100005
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[User]
				WHERE 
	(CASE WHEN @updLogin IS NOT NULL THEN (CASE WHEN [Login] = @updLogin THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @updPwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSalt IS NOT NULL THEN (CASE WHEN [Salt] = @updSalt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @updFriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @updUserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @updUserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[User]
	WHERE 
	(CASE WHEN @Login IS NOT NULL THEN (CASE WHEN [Login] = @Login THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @PwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @PwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Salt IS NOT NULL THEN (CASE WHEN [Salt] = @Salt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @FirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @MiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @MiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @LastName IS NOT NULL THEN (CASE WHEN [LastName] = @LastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @FriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @FriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @UserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @UserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @UserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[User]
	WHERE 
	(CASE WHEN @updLogin IS NOT NULL THEN (CASE WHEN [Login] = @updLogin THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updPwdHash IS NOT NULL THEN (CASE WHEN [PwdHash] = @updPwdHash THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updSalt IS NOT NULL THEN (CASE WHEN [Salt] = @updSalt THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFirstName IS NOT NULL THEN (CASE WHEN [FirstName] = @updFirstName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updMiddleName IS NOT NULL THEN (CASE WHEN [MiddleName] = @updMiddleName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updLastName IS NOT NULL THEN (CASE WHEN [LastName] = @updLastName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updFriendlyName IS NOT NULL THEN (CASE WHEN [FriendlyName] = @updFriendlyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserStatusID IS NOT NULL THEN (CASE WHEN [UserStatusID] = @updUserStatusID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updUserTypeID IS NOT NULL THEN (CASE WHEN [UserTypeID] = @updUserTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'User was not updated', 1
END