version: '3.4'

services:
  ppt_photoprint_sqldb:
    image: "globus000/ppt.photoprint.sqldb"
    ports:
      - "2433:1433"
    networks:
      - ppt_photoprint_backend
      
  ppt_photoprint_api:
    image: "globus000/ppt.photoprint.api"
    environment:
      - ServiceConfig__DalInitParams__ConnectionString=Data Source=ppt_photoprint_sqldb; Initial Catalog=PhotoPrint; User ID=ppt_svc_api; Password=PPTServiceApi2021!
      - ServiceConfig__StorageInitParams__StorageConnectionString=BlobEndpoint=https://photoprintstorage.blob.core.windows.net/;QueueEndpoint=https://photoprintstorage.queue.core.windows.net/;FileEndpoint=https://photoprintstorage.file.core.windows.net/;TableEndpoint=https://photoprintstorage.table.core.windows.net/;SharedAccessSignature=sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-12-05T04:11:36Z&st=2021-12-04T20:11:36Z&spr=https&sig=kZlrAy53M2nZF7YXrcKuOQuR70%2Bea15mwD4i3ib860A%3D
      - ServiceConfig__StorageInitParams__StorageUrl=https://photoprintstorage.blob.core.windows.net
      - ServiceConfig__StorageInitParams__ContainerName=photoprint-images-dev
    ports: 
      - "8082:8082"
    networks:
      - ppt_photoprint_backend
    depends_on:
      - ppt_photoprint_sqldb
      
networks:
  ppt_photoprint_backend:
    driver: bridge