

DECLARE @ID BIGINT = NULL
DECLARE @SizeName NVARCHAR(50) = 'SizeName b5c1ceaf194f4c51bbdb08ffc9020da2'
DECLARE @Width INT = 255
DECLARE @Height INT = 255
DECLARE @IsDeleted BIT = 0
DECLARE @CreatedDate DATETIME = '6/27/2020 9:29:33 PM'
DECLARE @CreatedByID BIGINT = 100007
DECLARE @ModifiedDate DATETIME = '5/7/2019 3:18:33 PM'
DECLARE @ModifiedByID BIGINT = 100006
 

DELETE FROM [Size]
FROM 
	[dbo].[Size] e
WHERE
	(CASE WHEN @SizeName IS NOT NULL THEN (CASE WHEN [SizeName] = @SizeName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Width IS NOT NULL THEN (CASE WHEN [Width] = @Width THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Height IS NOT NULL THEN (CASE WHEN [Height] = @Height THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
