


DECLARE @ID BIGINT = NULL
DECLARE @UserID BIGINT = 100005
DECLARE @Url NVARCHAR(1000) = 'Url 934ac3e55b294a37a28585972f71a81c'
 

DELETE FROM [UserInteriorThumbnail]
FROM 
	[dbo].[UserInteriorThumbnail] e
WHERE
	(CASE WHEN @UserID IS NOT NULL THEN (CASE WHEN [UserID] = @UserID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Url IS NOT NULL THEN (CASE WHEN [Url] = @Url THEN 1 ELSE 0 END) ELSE 1 END) = 1 
