

-- original values --
DECLARE @ID BIGINT = NULL
DECLARE @AddressTypeID BIGINT = 4
DECLARE @Title NVARCHAR(50) = 'Title 85bff4401e9a4d1b8fedb35a369035bf'
DECLARE @CityID BIGINT = 2
DECLARE @Street NVARCHAR(50) = 'Street 85bff4401e9a4d1b8fedb35a369035bf'
DECLARE @BuildingNo NVARCHAR(50) = 'BuildingNo 85bff4401e9a4d1b8fedb35a369035bf'
DECLARE @ApartmentNo NVARCHAR(50) = 'ApartmentNo 85bff4401e9a4d1b8fedb35a369035bf'
DECLARE @Comment NVARCHAR(1000) = 'Comment 85bff4401e9a4d1b8fedb35a369035bf'
DECLARE @CreatedByID BIGINT = 100011
DECLARE @CreatedDate DATETIME = '10/8/2020 1:56:32 PM'
DECLARE @ModifiedByID BIGINT = 100004
DECLARE @ModifiedDate DATETIME = '10/8/2020 1:56:32 PM'
DECLARE @IsDeleted BIT = 1
 
-- updated values --

DECLARE @updID BIGINT = NULL
DECLARE @updAddressTypeID BIGINT = 5
DECLARE @updTitle NVARCHAR(50) = 'Title 234dadaa56194b089b0c097361f548a0'
DECLARE @updCityID BIGINT = 1
DECLARE @updStreet NVARCHAR(50) = 'Street 234dadaa56194b089b0c097361f548a0'
DECLARE @updBuildingNo NVARCHAR(50) = 'BuildingNo 234dadaa56194b089b0c097361f548a0'
DECLARE @updApartmentNo NVARCHAR(50) = 'ApartmentNo 234dadaa56194b089b0c097361f548a0'
DECLARE @updComment NVARCHAR(1000) = 'Comment 234dadaa56194b089b0c097361f548a0'
DECLARE @updCreatedByID BIGINT = 100005
DECLARE @updCreatedDate DATETIME = '8/18/2023 2:23:32 PM'
DECLARE @updModifiedByID BIGINT = 100010
DECLARE @updModifiedDate DATETIME = '8/18/2023 2:23:32 PM'
DECLARE @updIsDeleted BIT = 1
 

DECLARE @Fail AS BIT = 0

IF(NOT EXISTS(SELECT 1 FROM 
				[dbo].[Address]
				WHERE 
	(CASE WHEN @updAddressTypeID IS NOT NULL THEN (CASE WHEN [AddressTypeID] = @updAddressTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updTitle IS NOT NULL THEN (CASE WHEN [Title] = @updTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCityID IS NOT NULL THEN (CASE WHEN [CityID] = @updCityID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updStreet IS NOT NULL THEN (CASE WHEN [Street] = @updStreet THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updBuildingNo IS NOT NULL THEN (CASE WHEN [BuildingNo] = @updBuildingNo THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updApartmentNo IS NOT NULL THEN (CASE WHEN [ApartmentNo] = @updApartmentNo THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updComment IS NOT NULL THEN (CASE WHEN [Comment] = @updComment THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @updIsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 
 ))
					
BEGIN

DELETE FROM 
	[dbo].[Address]
	WHERE 
	(CASE WHEN @AddressTypeID IS NOT NULL THEN (CASE WHEN [AddressTypeID] = @AddressTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Title IS NOT NULL THEN (CASE WHEN [Title] = @Title THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CityID IS NOT NULL THEN (CASE WHEN [CityID] = @CityID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Street IS NOT NULL THEN (CASE WHEN [Street] = @Street THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @BuildingNo IS NOT NULL THEN (CASE WHEN [BuildingNo] = @BuildingNo THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ApartmentNo IS NOT NULL THEN (CASE WHEN [ApartmentNo] = @ApartmentNo THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @Comment IS NOT NULL THEN (CASE WHEN [Comment] = @Comment THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @CreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @CreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @ModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @ModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @ModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 

	SET @Fail = 1
END
ELSE
BEGIN
DELETE FROM 
	[dbo].[Address]
	WHERE 
	(CASE WHEN @updAddressTypeID IS NOT NULL THEN (CASE WHEN [AddressTypeID] = @updAddressTypeID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updTitle IS NOT NULL THEN (CASE WHEN [Title] = @updTitle THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCityID IS NOT NULL THEN (CASE WHEN [CityID] = @updCityID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updStreet IS NOT NULL THEN (CASE WHEN [Street] = @updStreet THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updBuildingNo IS NOT NULL THEN (CASE WHEN [BuildingNo] = @updBuildingNo THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updApartmentNo IS NOT NULL THEN (CASE WHEN [ApartmentNo] = @updApartmentNo THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updComment IS NOT NULL THEN (CASE WHEN [Comment] = @updComment THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedByID IS NOT NULL THEN (CASE WHEN [CreatedByID] = @updCreatedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updCreatedDate IS NOT NULL THEN (CASE WHEN [CreatedDate] = @updCreatedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedByID IS NOT NULL THEN (CASE WHEN [ModifiedByID] = @updModifiedByID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updModifiedDate IS NOT NULL THEN (CASE WHEN [ModifiedDate] = @updModifiedDate THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @updIsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @updIsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 
END


IF(@Fail = 1) 
BEGIN
	THROW 51001, 'Address was not updated', 1
END