

DECLARE @ID BIGINT = NULL
DECLARE @ISO NVARCHAR(5) = 'ISO f'
DECLARE @CurrencyName NVARCHAR(50) = 'CurrencyName fe7eefa7307d4a6497e34aa82f0acdb8'
DECLARE @IsDeleted BIT = 1
 

DELETE FROM [Currency]
FROM 
	[dbo].[Currency] e
WHERE
	(CASE WHEN @ISO IS NOT NULL THEN (CASE WHEN [ISO] = @ISO THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CurrencyName IS NOT NULL THEN (CASE WHEN [CurrencyName] = @CurrencyName THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @IsDeleted IS NOT NULL THEN (CASE WHEN [IsDeleted] = @IsDeleted THEN 1 ELSE 0 END) ELSE 1 END) = 1 
