

DECLARE @ImageID BIGINT = 100038
DECLARE @RelatedImageID BIGINT = 100036
 

DELETE FROM [ImageRelated]
FROM 
	[dbo].[ImageRelated] e
WHERE
	(CASE WHEN @ImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @ImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @RelatedImageID IS NOT NULL THEN (CASE WHEN [RelatedImageID] = @RelatedImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
