


DECLARE @ImageID BIGINT = 100035
DECLARE @CategoryID BIGINT = 100002
 

DELETE FROM [ImageCategory]
FROM 
	[dbo].[ImageCategory] e
WHERE
	(CASE WHEN @ImageID IS NOT NULL THEN (CASE WHEN [ImageID] = @ImageID THEN 1 ELSE 0 END) ELSE 1 END) = 1 AND
	(CASE WHEN @CategoryID IS NOT NULL THEN (CASE WHEN [CategoryID] = @CategoryID THEN 1 ELSE 0 END) ELSE 1 END) = 1 
